{% set name = "teachopencadd" %}
{% set version = "2022.09.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/volkamerlab/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: 8414091c3d6340e87e34d504c75e0a4733eaf9a89b847dfdd1a2c8c6e6589fd6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - teachopencadd = teachopencadd.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jupyter
    - jupyterlab >=3
    - nglview >=3
    - ipywidgets >=7.5
    - numpy
    - scikit-learn
    - tensorflow >=2.0
    - h5py <3.0.0
    - seaborn
    - matplotlib-venn
    - jsonschema <4.0.0
    - bravado
    - requests
    - requests-cache
    - redo
    - suds-community
    - beautifulsoup4
    - chembl_webresource_client
    - pypdb
    - biopython <=1.77
    - biopandas
    - rdkit ==2021.09.5
    - openbabel
    - opencadd
    - biotite
    - smina
    - mdanalysis >=1.0.0
    - mdtraj
    - plip
    - openmm
    - pdbfixer
    - tqdm
    - lxml
    - kissim

test:
  requires:
    - pip
  imports:
    - teachopencadd
  commands:
    - teachopencadd

about:
  home: https://github.com/volkamerlab/teachopencadd
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  summary: 'TeachOpenCADD: a teaching platform for computer-aided drug design (CADD) using open source packages and data'
  description: |
    TeachOpenCADD is a teaching platform for computer-aided drug design (CADD). 
    The platform offers pipelines used in the fields of cheminformatics and structural bioinformatics to answer central CADD questions.
    The pipelines are written in Python and are set up as Jupyter notebooks, covering both the theoretical background as well as the hands-on programming parts of a CADD topic.
  doc_url: https://projects.volkamerlab.org/teachopencadd/
  dev_url: https://github.com/volkamerlab/teachopencadd

extra:
  recipe-maintainers:
    - dominiquesydow
    - jaimergp
